### ISSUE TITLE
Gtk-dark

### ISSUE THREAD

**Issue by erikdubois** [osendott/arch-frost-gtk-dark#2]
making an installation script at https://github.com/erikdubois/themes-icons-pack
Is it true that your theme has no border theme as nothing shows up in there? Or is it again my computer...

**Comment by osendott** [comment]
There should be a dropshadow around the windows is that what you're referring to?

**Comment by erikdubois** [comment]
the written language ...
I put your two theme folders in .themes and go in linux mint 17.1 to the settings

you can change them in themes. Several options are available

window borders -  no arch here ? is this correct ?
icons - normal that there is no arch here
controls - here i find the two versions light and dark

My question is : Is it normal that there are no window borders for your arch theme?

**Comment by osendott** [comment]
oh I see the problem, sorry. There's no metacity theme.. Gnome uses CSS for window borders now, cinnamon still uses metacity. I'll see if I can locate the metacity folders and stick them back in the repo

**Comment by osendott** [comment]
ok metacity added back to the repo's.. grab it and stick with the rest, should work now :) sorry about that. Let me know how it looks, I didn't notice.
